### ISSUE TITLE
Colors dictionary needs more entries

### ISSUE THREAD

**Issue by anandvarma** [anandvarma/namegen#11]
With just 3 entries, it is fairly repetitive at this point. Populate the dictionary!

**Comment by gegaryfa** [comment]
hey @anandvarma , I see that a release was created based on the PR for this issue, but I can't update the dependency on my project. Apparently `go get` cannot find the latest v1.1 module. Do you know why ?

**Comment by anandvarma** [comment]
Traveling on work, will take a look at this issue over the weekend.
Did you try running `go clean -modcache` ?

**Comment by gegaryfa** [comment]
>Did you try running go clean -modcache ?

yup. I can only fetch v1.0.1

**Comment by anandvarma** [comment]
@gegaryfa, I pushed a new release v1.1.1, could you try and see if this works?

**Comment by gegaryfa** [comment]
> I pushed a new release v1.1.1, could you try and see if this works?

I worked now 🙌 . Thanks .
Out of curiosity, what was the issue ?

**Comment by anandvarma** [comment]
I think it was the fact that go was expecting a fully formed semantic version number like major.minor.patch 
Since the previous one, 1.1, didn't have a patch version, it seems to have failed. I should have named it 1.1.0 to avoid this issue. 
Anyway the new release, 1.1.1 has all 3 version components and it works now :)
