### ISSUE TITLE
Extend the dictionary_test to spot duplicates across dictionaries

### ISSUE THREAD

**Issue by anandvarma** [anandvarma/namegen#6]
Today there exists logic to detect duplicates within a given dictionary of words. We need to add a test to spot duplicates across dictionaries too. For instance colors might show up in the color and adjective dictionaries which when used together could end up creating names with duplicate words in them.

**Comment by rafiramadhana** [comment]
Hi @anandvarma ,

I can help with this.

It looks like the test that you're mentioning is [TestDictionarySanity](https://github.com/anandvarma/namegen/blob/main/dictionary_test.go#L8), CMIIW.

As we are going to have one more test scenario, which is "to spot duplicates across dictionaries", what if we update this TestDictionarySanity to have 2 subtests:
- TestDictionarySanity/ShouldBeSortedAndNotHaveDuplicateOnEachDictionary --> The existing one that you've written
- TestDictionarySanity/ShouldNotHaveDuplicateAcrossDictionaries --> The new one that I will add

Wdyt? Thanks

**Comment by anandvarma** [comment]
Hi @neverbeenthisweeb, thanks for reaching out to help.
You got it exactly right! Please go ahead and send in the PR and I'll be happy to review and get it merged as soon as possible.

**Comment by rafiramadhana** [comment]
@anandvarma 
Ok, I've created the PR in #7 .

Thank you.
